kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem