kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blog-django-py-git
spec:
  #host: blog-django-py-git-&metadata-namespace.apps.na46.prod.nextcle.com
  to:
    kind: Service
    name: blog-django-py-git
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
